apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-todo-ui-svc
spec:
  type: ClusterIP
  selector:
    app: {{ .Release.Name }}-todo-ui
  ports:
    - port: {{ .Values.todo-ui.ServicePort }}
      targetPort: {{ .Values.todo-ui.port }}